name: border_queue_management_app
description: A Flutter application for border queue management.

environment:
  sdk: '^2.12.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  qr_code_scanner: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true