name: Serverless Deployment

on:
  push:
    branches:
      - main
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Authenticate with Serverless
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: npx serverless login

      - name: Set deployment stage
        id: set-stage
        run: |
          if [ "${{ github.ref }}" == "refs/heads/release" ]; then
            echo "stage=prod" >> $GITHUB_ENV
          else
            echo "stage=dev" >> $GITHUB_ENV
          fi

      - name: Deploy to Serverless
        run: npx serverless deploy --stage ${{ env.stage }}
